const ADD_SAVED_PRODUCT_REQUEST = 'ADD_SAVED_PRODUCT_REQUEST';
const ADD_SAVED_PRODUCT_SUCCESS = 'ADD_SAVED_PRODUCT_SUCCESS';
const ADD_SAVED_PRODUCT_FAILRUE = 'ADD_SAVED_PRODUCT_FAILRUE';

const REMOVE_SAVED_PRODUCT_REQUEST = 'REMOVE_SAVED_PRODUCT_REQUEST';
const REMOVE_SAVED_PRODUCT_SUCCESS = 'REMOVE_SAVED_PRODUCT_SUCCESS';
const REMOVE_SAVED_PRODUCT_FAILURE = 'REMOVE_SAVED_PRODUCT_FAILURE';

const GET_SAVED_PRODUCTS_REQUEST = 'GET_SAVED_PRODUCTS_REQUEST';
const GET_SAVED_PRODUCTS_SUCCESS = 'GET_SAVED_PRODUCTS_SUCCESS';
const GET_SAVED_PRODUCTS_FAILURE = 'GET_SAVED_PRODUCTS_FAILURE';

const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';

const SET_USER = 'SET_USER';
const SET_USER_FAILURE = 'SET_USER_FAILURE';
const UPDATE_USER = 'UPDATE_USER';
const UPDATE_FILTER = 'UPDATE_FILTER';
const UPDATE_PRODUCT_CREATION = 'UPDATE_PRODUCT_CREATION';
const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS'

const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const GET_OWNER_DETAILS_REQUEST = 'GET_OWNER_DETAILS_REQUEST';
const GET_OWNER_DETAILS_SUCCESS = 'GET_OWNER_DETAILS_SUCCESS';
const GET_OWNER_DETAILS_FAILURE = 'GET_OWNER_DETAILS_FAILURE';

const GET_CURRENT_USER_REQUEST = 'GET_CURRENT_USER_REQUEST';
const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';
const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

const SET_NEW_PRODUCT_DETAILS = 'SET_NEW_PRODUCT_DETAILS';

const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
const GET_PRODUCT_DETAILS_FAILURE = "GET_PRODUCT_DETAILS_FAILURE";


const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

const RECEIVED_MESSAGE = "RECEIVED_MESSAGE";
const CHAT_HISTORY_REQUEST = "CHAT_HISTORY_REQUEST"
const CHAT_HISTORY_SUCCESS = "CHAT_HISTORY_SUCCESS";

const INITIALIZE_CONSTANTS = "INITIALIZE_CONSTANTS";
const CHAT_VISITED = "CHAT_VISITED";


const MESSAGES_INFO_REQUEST = "MESSAGES_INFO_REQUEST";
const MESSAGES_INFO_SUCCESS = "MESSAGES_INFO_SUCCESS";
const MESSAGES_INFO_FAILURE = "MESSAGES_INFO_FAILURE";

const BUSY_INDICATOR = "BUSY_INDICATOR";

const INCOMING_PRODUCTS_REQUEST = "INCOMING_PRODUCTS_REQUEST";
const INCOMING_PRODUCTS_FAILURE = "INCOMING_PRODUCTS_FAILURE";
const INCOMING_PRODUCTS_SUCCESS = "INCOMING_PRODUCTS_SUCCESS";

const OUTGOING_PRODUCTS_REQUEST = "OUTGOING_PRODUCTS_REQUEST";
const OUTGOING_PRODUCTS_FAILURE = "OUTGOING_PRODUCTS_FAILURE";
const OUTGOING_PRODUCTS_SUCCESS = "OUTGOING_PRODUCTS_SUCCESS";

const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";
const ORDER_RESET = "ORDER_RESET";

const PAYMENT_REQUEST = "PAYMENT_REQUEST";
const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
const PAYMENT_FAILURE = "PAYMENT_FAILURE";
const PAYMENT_RESET = "PAYMENT_RESET";
export {
	ADD_SAVED_PRODUCT_REQUEST,
	ADD_SAVED_PRODUCT_SUCCESS,
	ADD_SAVED_PRODUCT_FAILRUE,
	
	REMOVE_SAVED_PRODUCT_REQUEST,
	REMOVE_SAVED_PRODUCT_SUCCESS,
	REMOVE_SAVED_PRODUCT_FAILURE,
	
	GET_SAVED_PRODUCTS_REQUEST,
	GET_SAVED_PRODUCTS_SUCCESS,
	GET_SAVED_PRODUCTS_FAILURE,

	SEARCH_PRODUCTS_REQUEST,
	SEARCH_PRODUCTS_SUCCESS,
	SEARCH_PRODUCTS_FAILURE,

	SET_USER,
	SET_USER_FAILURE,

	UPDATE_USER,
	UPDATE_FILTER,
	UPDATE_PRODUCT_CREATION,
	SET_PRODUCT_DETAILS,

	LOGIN_REQUEST,
	LOGIN_SUCCESS,
	LOGIN_FAILURE,

	GET_OWNER_DETAILS_REQUEST,
	GET_OWNER_DETAILS_SUCCESS,
	GET_OWNER_DETAILS_FAILURE,

	GET_CURRENT_USER_REQUEST,
	GET_CURRENT_USER_SUCCESS,
	GET_CURRENT_USER_FAILURE,

	SET_NEW_PRODUCT_DETAILS,
	GET_PRODUCT_DETAILS_REQUEST,
	GET_PRODUCT_DETAILS_SUCCESS,
	GET_PRODUCT_DETAILS_FAILURE,

	SEND_MESSAGE_REQUEST,
	SEND_MESSAGE_SUCCESS,
	SEND_MESSAGE_FAILURE,

	RECEIVED_MESSAGE,
	CHAT_HISTORY_REQUEST,
	CHAT_HISTORY_SUCCESS,
	INITIALIZE_CONSTANTS,
	CHAT_VISITED,

	MESSAGES_INFO_REQUEST,
	MESSAGES_INFO_SUCCESS,
	MESSAGES_INFO_FAILURE,

	BUSY_INDICATOR,

	INCOMING_PRODUCTS_REQUEST,
	INCOMING_PRODUCTS_FAILURE,
	INCOMING_PRODUCTS_SUCCESS,

	OUTGOING_PRODUCTS_REQUEST,
	OUTGOING_PRODUCTS_FAILURE,
	OUTGOING_PRODUCTS_SUCCESS,

	CREATE_ORDER_REQUEST,
	CREATE_ORDER_SUCCESS,
	CREATE_ORDER_FAILURE,
	ORDER_RESET,

	PAYMENT_REQUEST,
	PAYMENT_SUCCESS,
	PAYMENT_FAILURE,
	PAYMENT_RESET
}